# Use Ubuntu 22.04 as the base image
FROM ubuntu:jammy-20240911.1

# Set environment variable to avoid prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive

# Add build arguments for the custom APT repository and User-Agent
ARG APT_REPO_URL
ARG APT_USER_AGENT="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"

# Update the package index and install the required packages in a single layer
RUN if [ -n "$APT_REPO_URL" ]; then \
        echo "deb ${APT_REPO_URL} jammy main restricted universe multiverse" > /etc/apt/sources.list && \
        echo "deb ${APT_REPO_URL} jammy-security main restricted universe multiverse" >> /etc/apt/sources.list; \
    fi && \
    if [ -n "$APT_USER_AGENT" ]; then \
        echo "Acquire::http::User-Agent \"${APT_USER_AGENT}\";" > /etc/apt/apt.conf.d/99custom-user-agent; \
    fi && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
    coreutils \
    man-db \
    openssh-client \
    git \
    rsync \
    gnupg \
    curl \
    wget \
    netcat \
    socat \
    iputils-ping \
    ldap-utils \
    iperf3 \
    lsof \
    zip \
    unzip \
    gzip \
    wrk \
    iproute2 \
    traceroute \
    dnsutils \
    tcpdump \
    tree \
    jq \
    less \
    tmux \
    xclip \
    nano \
    gettext-base \
    locales && \
    # Clean up the apt cache to reduce image size
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* \
    && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8

ENV LANG=en_US.utf8
