# when using docker compose command against this docker-compose file,
# please make sure .env exists with following environment variables:
# LDAP_USERNAME
# LDAP_PASSWORD
services:
    test-gitlab:
        image: docker-group.repo.svc.internal/gitlab/gitlab-ce:18.5.0-ce.0
        shm_size: '1gb'
        container_name: test-gitlab
        restart: always
        #healthcheck:
          #disable: true
        environment:
            GITLAB_OMNIBUS_CONFIG: |
                external_url "http://192.168.201.83:63088"
                nginx['listen_port'] = 4080
                gitlab_rails['gitlab_shell_ssh_port'] = 63089
                gitlab_rails['lfs_enabled'] = true
                gitlab_rails['manage_backup_path'] = true
                gitlab_rails['backup_path'] = "/var/opt/gitlab/backups"
                gitlab_rails['backup_keep_time'] = 1800
                gitlab_rails['ldap_enabled'] = true
                gitlab_rails['prevent_ldap_sign_in'] = false
                gitlab_rails['ldap_servers'] = {
                        'main' => {
                                'label' => 'zoo AD',
                                'host' =>  'ldap.oa.internal',
                                'port' => 389,
                                'uid' => 'sAMAccountName',
                                'bind_dn' => '${LDAP_USERNAME}',
                                'password' => '${LDAP_PASSWORD}',
                                'encryption' => 'plain',
                                'verify_certificates' => false,
                                'active_directory' => true,
                                'allow_username_or_email_login' => true,
                                'base' => 'dc=oa,dc=internal',
                                'lowercase_usernames' => true,
                                'block_auto_created_users' => true
                        }
                }
                gitlab_rails['gitlab_email_enabled'] = false
                pages_external_url "https://gitlab-pages.svc.internal"
                gitlab_pages['enable'] = true
                gitlab_pages['access_control'] = true
                pages_nginx['enable'] = true
                pages_nginx['listen_port'] = 4080
                pages_nginx['listen_https'] = false
        volumes:
            - /opt/test-gitlab/config:/etc/gitlab
            - /opt/test-gitlab/logs:/var/log/gitlab
            - /opt/test-gitlab/data:/var/opt/gitlab
        ports:
            - "63088:4080"
            - "63089:22"
        networks:
            - devops-lan
networks:
    devops-lan:
        external: true
