apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: devops

commonLabels:
  app.kubernetes.io/name: adminer

images:
- name: adminer
  newName: adminer
  newTag: 5.4.2-standalone

# ~1 is how JSON Pointer escapes /, so the annotation key iam.gke.io/gcp-service-account must be written as iam.gke.io~1gcp-service-account
patches:
- target:
    kind: HTTPRoute
    name: adminer
  patch: |
    - op: add
      path: /spec/hostnames/0
      value: adminer.svc.internal
    - op: add
      path: /spec/parentRefs/0/name
      value: multi-protocol-gateway
    - op: add
      path: /spec/parentRefs/0/namespace
      value: devops
    - op: add
      path: /spec/parentRefs/0/sectionName
      value: https-zoo-svc-wildcard