workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
default:
  tags:
    - all
    - hpc
variables:
  CI_APPLICATION_REPOSITORY: "docker-group.repo.svc.internal/python"
  CI_APPLICATION_TAG: "3.10.12-bookworm-poetry2.1.4"
  CS_SEVERITY_THRESHOLD: "HIGH"
  SAST_SEMGREP_METRICS: "false"
include:
  - template: Jobs/SAST.gitlab-ci.yml
  - template: Jobs/SAST-IaC.gitlab-ci.yml
  - template: Jobs/Container-Scanning.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml