apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secrets-operator
spec:
  project: need-to-override
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault-secrets-operator
    targetRevision: 1.3.0
    helm:
      releaseName: vso
      valuesObject:
        controller:
          manager:
            globalTransformationOptions:
              excludeRaw: true
            globalVaultAuthOptions:
              allowDefaultGlobals: true
        defaultVaultConnection:
          enabled: true
          address: "http://vault.vault.svc:8200"
        defaultAuthMethod:
          enabled: true
          namespace: configure-this-for-namespaced-vault
          method: kubernetes
          mount: kubernetes
          kubernetes:
            role: vault-k8s-devops
            serviceAccount: default
            tokenAudiences: ['vault']
  destination:
    server: need-to-override
    namespace: vault-secrets-operator
  syncPolicy:
    automated:
      enabled: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
