apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-resources
spec:
  project: need-to-override
  source:
    repoURL: need-to-override
    path: scripts/kubernetes/apps/devops/cert-manager-resources/overlays/dev
    targetRevision: HEAD
  destination:
    server: need-to-override
  syncPolicy:
    automated:
      enabled: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true