apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
authentication:
  webhook:
    enabled: true
authorization:
  mode: Webhook
# shutdownGracePeriod: 30s
# shutdownGracePeriodCriticalPods: 10s
