apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: gitlab-runner-all-01-token
spec:
  type: kv-v2
  mount: kv
  refreshAfter: 30s
  destination:
    type: Opaque
    name: gitlab-runner-all-01-token
    create: true
    overwrite: true
    transformation:
      excludes:
      - ".*"
      templates:
        runner-token:
          text: |-
            {{- printf (get .Secrets "runner-token") -}}
        runner-registration-token:
          text: ""