FROM wordpress:6.6.2-fpm

# Install required packages for the PHP LDAP extension
RUN apt-get update && \
    apt-get install -y libldap2-dev && \
    docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu && \
    docker-php-ext-install ldap && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
