apiVersion: v1
kind: Service
metadata:
  name: postgresql-external
  namespace: devops
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: postgresql
    app.kubernetes.io/name: postgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  externalIPs: []