@startuml
box Office #LightBlue
actor User
end box
box Wormhole
boundary Frontend as ReverseProxy
participant Backend as ActualServer
end box

User -[#blue]> ReverseProxy : http://127.0.0.1/api/login
activate ReverseProxy
ReverseProxy -[#blue]> ActualServer : http://w.x.y.z:8111/login
activate ActualServer
ActualServer -[#blue]> ReverseProxy : response
deactivate ActualServer
ReverseProxy -[#blue]> User : response
deactivate ReverseProxy
@enduml
