apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gateway_with_http_redirect.yaml
  - external_svc_gitlab.yaml
  - external_svc_nexus_repository.yaml
  - external_svc_kroki.yaml

namespace: devops