services:
  mysql:
    image: docker-group.repo.svc.internal/mysql:8.0.32
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - /opt/docker_volumes/mysql:/var/lib/mysql:Z
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    restart: always
    networks:
      devops-lan:
networks:
  devops-lan:
    external: true
