apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: argocd-notifications
spec:
  type: kv-v2
  mount: kv
  refreshAfter: 30s
  destination:
    type: Opaque
    name: argocd-notifications-secret
    create: true
    overwrite: true
    transformation:
      excludes:
      - ".*"
      templates:
        telegram-token:
          text: |-
            {{- printf (get .Secrets "telegram-token") -}}