apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: awx-admin
spec:
  type: kv-v2
  mount: kv
  refreshAfter: 30s
  destination:
    type: Opaque
    name: awx-admin
    create: true
    overwrite: true
    transformation:
      excludes:
      - ".*"
      templates:
        password:
          text: |-
            {{- printf (get .Secrets "password") -}}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: awx-postgresql
spec:
  type: kv-v2
  mount: kv
  refreshAfter: 30s
  destination:
    type: Opaque
    name: awx-postgresql
    create: true
    overwrite: true
    transformation:
      excludes:
      - ".*"
      templates:
        database:
          text: awx
        host:
          text: postgresql.devops
        port:
          text: '5432'
        type:
          text: unmanaged
        username:
          text: awx
        password:  
          text: |-
            {{- printf (get .Secrets "password") -}}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: awx-secret-key
spec:
  type: kv-v2
  mount: kv
  refreshAfter: 30s
  destination:
    type: Opaque
    name: awx-secret-key
    create: true
    overwrite: true
    transformation:
      excludes:
      - ".*"
      templates:
        secret_key:
          text: |-
            {{- printf (get .Secrets "secret-key") -}}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: root-ca-cert
spec:
  type: kv-v2
  mount: kv
  refreshAfter: 30s
  destination:
    type: Opaque
    name: root-ca-cert
    create: true
    overwrite: true
    transformation:
      excludes:
      - ".*"
      templates:
        bundle-ca.crt:
          text: |-
            {{- printf (get .Secrets "tls.crt") -}}