- op: replace
  path: /spec/project
  value: devops
- op: replace
  path: /spec/source/repoURL
  value: ssh://git@192.168.201.83:8089/zoo/devops.git
- op: replace
  path: /spec/destination/server
  value: https://192.168.201.83:6443