apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  project: need-to-override
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.19.4
    helm:
      valuesObject:
        crds:
          enabled: true
          keep: true
        config:
          apiVersion: controller.config.cert-manager.io/v1alpha1
          kind: ControllerConfiguration
          enableGatewayAPI: true
  destination:
    server: need-to-override
    namespace: cert-manager
  syncPolicy:
    automated:
      enabled: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
