apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: root-ca-tls
spec:
  type: kv-v2
  mount: kv
  refreshAfter: 30s
  destination:
    type: kubernetes.io/tls
    name: zoo-dev-platform-root-ca-tls
    create: true
    overwrite: true
    transformation:
      excludes:
      - ".*"
      templates:
        tls.crt:
          text: |-
            {{- printf (get .Secrets "tls.crt") -}}
        tls.key:
          text: |-
            {{- printf (get .Secrets "tls.key") -}}